### ISSUE TITLE
Type system

### ISSUE THREAD

**Issue by daviddavo** [yoyurec/logseq-awesome-props#11]
**Problem**
I have a lot of pages of type Book with reviews and some data. The problem is that sometimes I forget to define one of the properties that I consider all Books should have. I solved this with a template called `Book` that has all these properties, and then using the Convert Block to Page plugin.

**Idea**
If a page has the property `page-type:: [[X]]`, automatically populate the rest of the properties. Kind of like templates, but just for properties. Perhaps we could even extend the system and implement inheritance. (If the page Y (which will be used as a type) has the property `type:: [[X]]`, it can _inherit_ the properties of X and then define some properties on its own).

**Example**
Imagine you have the type _Book_. All pages of type _Book_ will have an `author`, `isbn`, `url`,etc. properties. If you create a new page with `page-type: [[Book]]`, it would be nice if it "imported" the other properties (with default or null values).

**Implementation**
Some people won't want to inherit all the properties of the "Type Page". I propose an extra special property would be created for this kind of pages called something like `type-properties`, which has a list of the properties you would like to inherit.

Let's see an example, we have the page type `Book`.
> **Book.md**
> ```md
> type-properties:: Author, ISBN, url
> ```

If we create a new book, we would want a page like this:
> **Going Postal.md**
> ```md
> type:: [[Book]]
> Author:: null
> ISBN:: null
> url:: null
> ```

**Comment by yoyurec** [comment]
Plugin currently does not interact with content creating in any way - just READING and restyling it...

"Inheriting and auto-pasting props" is not about "props" themself _(which are just a text, a common block ("brick") of Logseq piece of content, that just has specific syntax and interprets as "props")_
So requested functionality is just about working with pieces of text. And workflow with these pieces in Logseq = templating.
And you are already using them ))
But instead of using them, you are suggesting "expanding" one text ( = `Inheriting and auto pasting props`) into another.
So type something, open the commands menu, and choose the command to expand - 3 actions.
Or the old way - open the commands menu, run template command, choose template - 3 actions )))

Questions:
* Are you sure you really want to change your current workflow?
* am i sure i want to spend a lot of time coding for the feature that already exists in the same "3 actions away from result"? ))
* Why don't use "text expander" os app?
* or Logseq plugin: https://github.com/sawhney17/logseq-smartblocks, https://github.com/sethyuan/logseq-plugin-smart-typing/blob/master/README.en.md

🤔

**Comment by yoyurec** [comment]
Hope it was clear and detailed ))
I'm personally using templates, but looks like it's time to look closer for suggested plugins too...

**Comment by daviddavo** [comment]
Yes, thank you very much. I think the only advantage would be being able to "refactor" a type (if you change the props, raise a warning of items with some missing property). Furthermore, I think implementing that would be out of scope of this plugin, and creating a new plugin wouldn't be much different from smartblocks.

Thank you very much for the recommendations!

**Comment by yoyurec** [comment]
there is also interesting "Supertags" plugin, have no played yet but looks it for block props, not page blocks
but as you wrote before - it's easy to convert to a page with "Convert Block to Page" plugin.

**Comment by hdansou** [comment]
@daviddavo take a look at the plugin power tags. It may have what you need.

**Comment by yoyurec** [comment]
> @daviddavo take a look at the plugin power tags. It may have what you need.

right, power tags. not super )
